In [64]:
import pandas as pd

In [65]:
data = pd.read_csv('/content/loan_data.csv')
data

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [66]:
data.shape

(45000, 14)

In [67]:
data.dtypes

person_age                        float64
person_gender                      object
person_education                   object
person_income                     float64
person_emp_exp                      int64
person_home_ownership              object
loan_amnt                         float64
loan_intent                        object
loan_int_rate                     float64
loan_percent_income               float64
cb_person_cred_hist_length        float64
credit_score                        int64
previous_loan_defaults_on_file     object
loan_status                         int64
dtype: object

In [68]:
from sklearn.preprocessing import LabelEncoder

In [69]:
a = LabelEncoder()

In [70]:
data['person_gender'] = a.fit_transform(data['person_gender'])

In [71]:
a = data.replace({'High School':0,'Associate':1,'Bachelor':2,'Master':3,'Doctorate':4})

/tmp/ipykernel_696/2744506579.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  a = data.replace({'High School':0,'Associate':1,'Bachelor':2,'Master':3,'Doctorate':4})

In [72]:
a

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,3,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,0,0,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,0,0,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,0,2,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,1,3,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,1,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,0,1,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,1,1,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,1,2,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,1,0,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [73]:
b = a.replace({'RENT':0,'OTHER':1,'MORTGAGE':2,'OWN':3})

/tmp/ipykernel_696/164116387.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  b = a.replace({'RENT':0,'OTHER':1,'MORTGAGE':2,'OWN':3})

In [74]:
b

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,3,71948.0,0,0,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,0,0,12282.0,0,3,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,0,0,12438.0,3,2,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,0,2,79753.0,0,0,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,1,3,66135.0,1,0,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,1,47971.0,6,0,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,0,1,65800.0,17,0,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,1,1,56942.0,7,0,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,1,2,33164.0,4,0,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,1,0,51609.0,1,0,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [75]:
g = b.replace({'No':0,'Yes':1})

/tmp/ipykernel_696/2893430931.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  g = b.replace({'No':0,'Yes':1})

In [76]:
g

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,3,71948.0,0,0,35000.0,PERSONAL,16.02,0.49,3.0,561,0,1
1,21.0,0,0,12282.0,0,3,1000.0,EDUCATION,11.14,0.08,2.0,504,1,0
2,25.0,0,0,12438.0,3,2,5500.0,MEDICAL,12.87,0.44,3.0,635,0,1
3,23.0,0,2,79753.0,0,0,35000.0,MEDICAL,15.23,0.44,2.0,675,0,1
4,24.0,1,3,66135.0,1,0,35000.0,MEDICAL,14.27,0.53,4.0,586,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,1,47971.0,6,0,15000.0,MEDICAL,15.66,0.31,3.0,645,0,1
44996,37.0,0,1,65800.0,17,0,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,0,1
44997,33.0,1,1,56942.0,7,0,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,0,1
44998,29.0,1,2,33164.0,4,0,12000.0,EDUCATION,13.23,0.36,6.0,604,0,1
44999,24.0,1,0,51609.0,1,0,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,0,1

In [77]:
h = g.drop(['cb_person_cred_hist_length'],axis=1)
h

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,3,71948.0,0,0,35000.0,PERSONAL,16.02,0.49,561,0,1
1,21.0,0,0,12282.0,0,3,1000.0,EDUCATION,11.14,0.08,504,1,0
2,25.0,0,0,12438.0,3,2,5500.0,MEDICAL,12.87,0.44,635,0,1
3,23.0,0,2,79753.0,0,0,35000.0,MEDICAL,15.23,0.44,675,0,1
4,24.0,1,3,66135.0,1,0,35000.0,MEDICAL,14.27,0.53,586,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,1,47971.0,6,0,15000.0,MEDICAL,15.66,0.31,645,0,1
44996,37.0,0,1,65800.0,17,0,9000.0,HOMEIMPROVEMENT,14.07,0.14,621,0,1
44997,33.0,1,1,56942.0,7,0,2771.0,DEBTCONSOLIDATION,10.02,0.05,668,0,1
44998,29.0,1,2,33164.0,4,0,12000.0,EDUCATION,13.23,0.36,604,0,1
44999,24.0,1,0,51609.0,1,0,6665.0,DEBTCONSOLIDATION,17.05,0.13,628,0,1

In [78]:
data = h
data

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,3,71948.0,0,0,35000.0,PERSONAL,16.02,0.49,561,0,1
1,21.0,0,0,12282.0,0,3,1000.0,EDUCATION,11.14,0.08,504,1,0
2,25.0,0,0,12438.0,3,2,5500.0,MEDICAL,12.87,0.44,635,0,1
3,23.0,0,2,79753.0,0,0,35000.0,MEDICAL,15.23,0.44,675,0,1
4,24.0,1,3,66135.0,1,0,35000.0,MEDICAL,14.27,0.53,586,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,1,47971.0,6,0,15000.0,MEDICAL,15.66,0.31,645,0,1
44996,37.0,0,1,65800.0,17,0,9000.0,HOMEIMPROVEMENT,14.07,0.14,621,0,1
44997,33.0,1,1,56942.0,7,0,2771.0,DEBTCONSOLIDATION,10.02,0.05,668,0,1
44998,29.0,1,2,33164.0,4,0,12000.0,EDUCATION,13.23,0.36,604,0,1
44999,24.0,1,0,51609.0,1,0,6665.0,DEBTCONSOLIDATION,17.05,0.13,628,0,1

In [79]:
data

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,3,71948.0,0,0,35000.0,PERSONAL,16.02,0.49,561,0,1
1,21.0,0,0,12282.0,0,3,1000.0,EDUCATION,11.14,0.08,504,1,0
2,25.0,0,0,12438.0,3,2,5500.0,MEDICAL,12.87,0.44,635,0,1
3,23.0,0,2,79753.0,0,0,35000.0,MEDICAL,15.23,0.44,675,0,1
4,24.0,1,3,66135.0,1,0,35000.0,MEDICAL,14.27,0.53,586,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,1,47971.0,6,0,15000.0,MEDICAL,15.66,0.31,645,0,1
44996,37.0,0,1,65800.0,17,0,9000.0,HOMEIMPROVEMENT,14.07,0.14,621,0,1
44997,33.0,1,1,56942.0,7,0,2771.0,DEBTCONSOLIDATION,10.02,0.05,668,0,1
44998,29.0,1,2,33164.0,4,0,12000.0,EDUCATION,13.23,0.36,604,0,1
44999,24.0,1,0,51609.0,1,0,6665.0,DEBTCONSOLIDATION,17.05,0.13,628,0,1

In [80]:
a = LabelEncoder()

In [81]:
data['loan_intent'] = a.fit_transform(data['loan_intent'])

In [82]:
data

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,0,3,71948.0,0,0,35000.0,4,16.02,0.49,561,0,1
1,21.0,0,0,12282.0,0,3,1000.0,1,11.14,0.08,504,1,0
2,25.0,0,0,12438.0,3,2,5500.0,3,12.87,0.44,635,0,1
3,23.0,0,2,79753.0,0,0,35000.0,3,15.23,0.44,675,0,1
4,24.0,1,3,66135.0,1,0,35000.0,3,14.27,0.53,586,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,1,1,47971.0,6,0,15000.0,3,15.66,0.31,645,0,1
44996,37.0,0,1,65800.0,17,0,9000.0,2,14.07,0.14,621,0,1
44997,33.0,1,1,56942.0,7,0,2771.0,0,10.02,0.05,668,0,1
44998,29.0,1,2,33164.0,4,0,12000.0,1,13.23,0.36,604,0,1
44999,24.0,1,0,51609.0,1,0,6665.0,0,17.05,0.13,628,0,1

In [83]:
data.isnull().sum()

person_age                        0
person_gender                     0
person_education                  0
person_income                     0
person_emp_exp                    0
person_home_ownership             0
loan_amnt                         0
loan_intent                       0
loan_int_rate                     0
loan_percent_income               0
credit_score                      0
previous_loan_defaults_on_file    0
loan_status                       0
dtype: int64

In [84]:
data.dtypes

person_age                        float64
person_gender                       int64
person_education                    int64
person_income                     float64
person_emp_exp                      int64
person_home_ownership               int64
loan_amnt                         float64
loan_intent                         int64
loan_int_rate                     float64
loan_percent_income               float64
credit_score                        int64
previous_loan_defaults_on_file      int64
loan_status                         int64
dtype: object

In [85]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [86]:
x = data.drop('loan_status',axis=1)
y = data['loan_status']

In [87]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [88]:
from collections import Counter

In [89]:
Counter(y_train)

Counter({0: 28010, 1: 7990})

In [90]:
from imblearn.over_sampling import SMOTE

In [91]:
a = SMOTE()

In [92]:
x_train_smt,y_train_smt = a.fit_resample(x_train,y_train)

In [93]:
Counter(y_train_smt)

Counter({0: 28010, 1: 28010})

LOGISTIC REGRESSION

In [94]:
model1 = LogisticRegression()
model1.fit(x_train_smt,y_train_smt)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [95]:
y_pred1 = model1.predict(x_test)
y_pred1

array([0, 1, 1, ..., 1, 1, 1])

In [96]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [97]:
ac1 = accuracy_score(y_test,y_pred1)
ac1

0.7716666666666666

DECISION TREE

In [98]:
from sklearn.tree import DecisionTreeClassifier

In [99]:
model2 = DecisionTreeClassifier(max_depth=5)
model2.fit(x_train_smt,y_train_smt)

DecisionTreeClassifier(max_depth=5)

In [100]:
y_pred2 = model2.predict(x_test)
y_pred2

array([0, 0, 1, ..., 0, 1, 1])

In [101]:
ac2 = accuracy_score(y_test,y_pred2)
ac2

0.897

RANDOM FOREST

In [102]:
from sklearn.ensemble import RandomForestClassifier

In [103]:
model3 = RandomForestClassifier(n_estimators=100)
model3.fit(x_train_smt,y_train_smt)

RandomForestClassifier()

In [104]:
y_pred3 = model3.predict(x_test)
y_pred3

array([0, 0, 1, ..., 0, 0, 1])

In [105]:
ac3 = accuracy_score(y_test,y_pred3)
ac3

0.9133333333333333

KNN

In [106]:
from sklearn.neighbors import KNeighborsClassifier

In [107]:
model4 = KNeighborsClassifier()
model4.fit(x_train_smt,y_train_smt)

KNeighborsClassifier()

In [108]:
y_pred4 = model4.predict(x_test)
y_pred4

array([0, 0, 0, ..., 0, 0, 1])

In [109]:
ac4 = accuracy_score(y_test,y_pred4)
ac4

0.7724444444444445

In [110]:
import pickle

pickle.dump(model3,open('model.pkl','wb'))

PREDICTION

In [113]:
age = int(input("Enter your age: "))
gender = int(input("Enter your gender(female:0,male:1): "))
education = int(input("Enter your education(highschool:0,associate:1,bachelor:2,master:3,doctorate:4): "))
income = int(input("Enter your income: "))
employment_experience = int(input("Enter experience: "))
home_ownership = int(input("Enter home ownership type(rent:0,other:1,mortagage:2,own:3): "))
loan_amount = int(input("Enter loan amount: "))
loan_intent = int(input("Enter loan intent(debtconsolidation:0,education:1,homeimprovement:2,medical:3,personal:4,venture:5): "))
loan_interest_rate = float(input("Enter loan interest rate: "))
loan_income_percent = float(input("Enter loan income percent: "))
credit_score = float(input("Enter credit score: "))
previous_defaults = int(input("Enter previous defaults(no:0,yes:1): "))

prediction = model3.predict([[age,gender,education,income,employment_experience,home_ownership,loan_amount,loan_intent,loan_interest_rate,loan_income_percent,credit_score,previous_defaults]])
print("LOAN APPROVAL: ",prediction[0])

Enter your age: 30
Enter your gender(female:0,male:1): 1
Enter your education(highschool:0,associate:1,bachelor:2,master:3,doctorate:4): 2
Enter your income: 50000
Enter experience: 5
Enter home ownership type(rent:0,other:1,mortagage:2,own:3): 3
Enter loan amount: 30000
Enter loan intent(debtconsolidation:0,education:1,homeimprovement:2,medical:3,personal:4,venture:5): 1
Enter loan interest rate: 10.8
Enter loan income percent: 0.49
Enter credit score: 504
Enter previous defaults(no:0,yes:1): 0
LOAN APPROVAL:  0

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(